- id: shfmt
  name: shfmt
  description: Format shell scripts with shfmt
  entry: shfmt
  language: python
  types: [shell]
  args: [-w] # write file back
  require_serial: true # shfmt can detect sourcing this way
