name: main

on:
  push:
    branches: [master, test-me-*]
    tags: '*'
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, macos-15-intel, windows-latest]
        python: ['3.9', '3.13', '3.14']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
      - run: pip install .
      - run: shfmt --version
      - run: shfmt --help
